# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0003_auto_20170910_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('phone', models.CharField(max_length=50, verbose_name='имя')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House', verbose_name='дом')),
            ],
        ),
    ]
